language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer validate --strict

install:
  - composer update --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit -c tests/phpunit.xml tests/
